require('lua-config/lsp-config')
require('lua-config/nvim-cmp-config')
--require('lua-config/nvim-compe-config')
require('lua-config/telescope-config')
require('lua-config/nvim-commenter-frame-config')
require('lua-config/gitsigns-config')
